// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYPJhvui1N1toAoCendU471ZRgbmsPKY',
    appId: '1:97042661428:web:097f70f82ce217272dca61',
    messagingSenderId: '97042661428',
    projectId: 'ludobyiamsouviki',
    authDomain: 'ludobyiamsouviki.firebaseapp.com',
    databaseURL: 'https://ludobyiamsouviki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludobyiamsouviki.firebasestorage.app',
    measurementId: 'G-JTB9S56SD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0MXaHTkxO6_m44_DoCACTvqgQZ2vQSDk',
    appId: '1:97042661428:android:da2b492c6370379b2dca61',
    messagingSenderId: '97042661428',
    projectId: 'ludobyiamsouviki',
    databaseURL: 'https://ludobyiamsouviki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludobyiamsouviki.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0DJZb9vMgWlf6K-xUuAKnnrSgRX6XpE',
    appId: '1:97042661428:ios:ca6c68fb5eba36bc2dca61',
    messagingSenderId: '97042661428',
    projectId: 'ludobyiamsouviki',
    databaseURL: 'https://ludobyiamsouviki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludobyiamsouviki.firebasestorage.app',
    iosBundleId: 'com.myludo.myLudo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0DJZb9vMgWlf6K-xUuAKnnrSgRX6XpE',
    appId: '1:97042661428:ios:ca6c68fb5eba36bc2dca61',
    messagingSenderId: '97042661428',
    projectId: 'ludobyiamsouviki',
    databaseURL: 'https://ludobyiamsouviki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludobyiamsouviki.firebasestorage.app',
    iosBundleId: 'com.myludo.myLudo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzYPJhvui1N1toAoCendU471ZRgbmsPKY',
    appId: '1:97042661428:web:3d12a41405873ab52dca61',
    messagingSenderId: '97042661428',
    projectId: 'ludobyiamsouviki',
    authDomain: 'ludobyiamsouviki.firebaseapp.com',
    databaseURL: 'https://ludobyiamsouviki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludobyiamsouviki.firebasestorage.app',
    measurementId: 'G-18GB9KE1EN',
  );
}
