// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0xp_kdfLfzk-z1fo5BUokn6btaZAbrfA',
    appId: '1:94304183673:web:6f616796a3fd09a1afbba8',
    messagingSenderId: '94304183673',
    projectId: 'my-ludo-73080',
    authDomain: 'my-ludo-73080.firebaseapp.com',
    databaseURL: 'https://my-ludo-73080-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-ludo-73080.firebasestorage.app',
    measurementId: 'G-7R48PJJ77G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ39qxmLb_JOikf_RzAoFgrG-Tgx2soLs',
    appId: '1:94304183673:android:9ff71b362fbb0d30afbba8',
    messagingSenderId: '94304183673',
    projectId: 'my-ludo-73080',
    databaseURL: 'https://my-ludo-73080-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-ludo-73080.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUI3318Zo3s9BimvxSEDuzjCxILm7w5s',
    appId: '1:94304183673:ios:8c3cc69f2b75547cafbba8',
    messagingSenderId: '94304183673',
    projectId: 'my-ludo-73080',
    databaseURL: 'https://my-ludo-73080-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-ludo-73080.firebasestorage.app',
    iosBundleId: 'com.myludo.myLudo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUI3318Zo3s9BimvxSEDuzjCxILm7w5s',
    appId: '1:94304183673:ios:8c3cc69f2b75547cafbba8',
    messagingSenderId: '94304183673',
    projectId: 'my-ludo-73080',
    databaseURL: 'https://my-ludo-73080-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-ludo-73080.firebasestorage.app',
    iosBundleId: 'com.myludo.myLudo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0xp_kdfLfzk-z1fo5BUokn6btaZAbrfA',
    appId: '1:94304183673:web:b8c2a4c1704ce9deafbba8',
    messagingSenderId: '94304183673',
    projectId: 'my-ludo-73080',
    authDomain: 'my-ludo-73080.firebaseapp.com',
    databaseURL: 'https://my-ludo-73080-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-ludo-73080.firebasestorage.app',
    measurementId: 'G-C8CX63V7B2',
  );
}
